name: Follow Workflow

on:
  push:
    branches:
      - main

jobs:
  upload:
    uses: ./.github/workflows/upload-steps.yml

  download:
    needs: upload
    runs-on: windows-latest

    steps:
      - name: Download artifact drop
        uses: actions/download-artifact@v4
        with:
          name: artifactOne
