name: Follow Workflow

on:
    push:
      branches:
        - main

jobs:
    upload:
        runs-on: windows-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
              
          - name: Create artifact drop
            uses: actions/upload-artifact@v4
            with:
              name: artifactOne
              path: files
    
    download:
        needs: upload
        runs-on: windows-latest

        steps:

          - name: Download artifact drop
            uses: actions/download-artifact@v4
            with:
              name: artifactOne
